language: csharp
mono: none
dotnet: 3.1.100
script:
- dotnet restore
- dotnet build ./HAC.API/
deploy:
  provider: heroku
  api_key:
    secure: "Ob1lINPE9gy2B6fvxokHDf/ylVUllYyGMs3zFdBT1LBhg8Qjuc0Le0LAbTAMN4OHrFGsA7NQCdbJPGqHZrsCdfdnOpWn6p/qdB+BfNMUk3LPL71tjBAHqe+gQ6kzoNT3XkFppTjpllXAgGfMp8ZeZkiRZmcdYmd3urrD7OgsikiWSvpbe3W32D14Xs1PiJYi7xR4JGuJ/HtCmjx985PPi9Ym6HjqSsllHUdYhLVjnLszGcNkciYr1Iphz5ETKkd6yQsDnXeuE9airBM4oN446YzozmeN+od8xQSPl1AOuPbLD5GfhLgQB3gGNLsT9iw6FjB+y9sVmwuanf030qZXU7yOu2aYWnKym7EJpIi0Ye8rFChvEOk2bw4ja7DYqVe4cX1XVz0TbJSIiRddZBZ8cvMSXildxfmzYFFkd+qq3VJdvucVzs4L+1c7zrNQnIMaJJwSc9bCBAU2Ey3RN5xDAXdmTLFlq9u36TIaMWRIPRwxStfObCIPCS7tByuj9w/3vf9NrJC+hrbTueSEQmq+jcIjw7ZwwyddCo8ab3XA4sk5kULpFNYtDSo5eYwwLm2KHQ7HxyJmtq8MttWa3+QiocloWH/QYnKc6k1aaDgs/04c280yMUU4QWiWxREMB0pStmDAYKaAF1xMxrVQ+dHASaco95jQHQI/ClkOAWRp3ek=" 
  app: hac-web-api