language: csharp
mono: none
dotnet: 3.1.100
script:
- dotnet restore
- dotnet build ./HomeAccessCenter-Web-API/
deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY" 
  app: hac-web-api